version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
      - '4000:4000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - config/docker.env
    stdin_open: true
    tty: true
    depends_on:
      - database

  assets:
    build: .
    command: bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - config/docker.env
    stdin_open: true
    tty: true

  database:
    image: postgres:12.4
    env_file:
      - config/docker.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - '5900:5900'

volumes:
  db_data:
